local Attach = require("dapc.rpc.request.Attach")
local BreakpointLocations = require("dapc.rpc.request.BreakpointLocations")
local Completions = require("dapc.rpc.request.Completions")
local ConfigurationDone = require("dapc.rpc.request.ConfigurationDone")
local Continue = require("dapc.rpc.request.Continue")
local DataBreakpointInfo = require("dapc.rpc.request.DataBreakpointInfo")
local Disassemble = require("dapc.rpc.request.Disassemble")
local Disconnect = require("dapc.rpc.request.Disconnect")
local Evaluate = require("dapc.rpc.request.Evaluate")
local ExceptionInfo = require("dapc.rpc.request.ExceptionInfo")
local Goto = require("dapc.rpc.request.Goto")
local GotoTargets = require("dapc.rpc.request.GotoTargets")
local Initialize = require("dapc.rpc.request.Initialize")
local Launch = require("dapc.rpc.request.Launch")
local LoadedSources = require("dapc.rpc.request.LoadedSources")
local Locations = require("dapc.rpc.request.Locations")
local Modules = require("dapc.rpc.request.Modules")
local Next = require("dapc.rpc.request.Next")
local Pause = require("dapc.rpc.request.Pause")
local ReadMemory = require("dapc.rpc.request.ReadMemory")
local Restart = require("dapc.rpc.request.Restart")
local RestartFrame = require("dapc.rpc.request.RestartFrame")
local ReverseContinue = require("dapc.rpc.request.ReverseContinue")
local Scopes = require("dapc.rpc.request.Scopes")
local SetBreakpoints = require("dapc.rpc.request.SetBreakpoints")
local SetDataBreakpoints = require("dapc.rpc.request.SetDataBreakpoints")
local SetExceptionBreakpoints = require("dapc.rpc.request.SetExceptionBreakpoints")
local SetFunctionBreakpoints = require("dapc.rpc.request.SetFunctionBreakpoints")
local SetInstructionBreakpoints = require("dapc.rpc.request.SetInstructionBreakpoints")
local SetVariable = require("dapc.rpc.request.SetVariable")
local Source = require("dapc.rpc.request.Source")
local StackTrace = require("dapc.rpc.request.StackTrace")
local StepBack = require("dapc.rpc.request.StepBack")
local StepIn = require("dapc.rpc.request.StepIn")
local StepInTargets = require("dapc.rpc.request.StepInTargets")
local StepOut = require("dapc.rpc.request.StepOut")
local Terminate = require("dapc.rpc.request.Terminate")
local TerminateThreads = require("dapc.rpc.request.TerminateThreads")
local Threads = require("dapc.rpc.request.Threads")
local Variables = require("dapc.rpc.request.Variables")
local WriteMemory = require("dapc.rpc.request.WriteMemory")

local COMMAND = require("dapc.rpc.request.Request").COMMAND

local M = {
	Attach = Attach,
	BreakpointLocations = BreakpointLocations,
	Completions = Completions,
	ConfigurationDone = ConfigurationDone,
	Continue = Continue,
	DataBreakpointInfo = DataBreakpointInfo,
	Disassemble = Disassemble,
	Disconnect = Disconnect,
	Evaluate = Evaluate,
	ExceptionInfo = ExceptionInfo,
	Goto = Goto,
	GotoTargets = GotoTargets,
	Initialize = Initialize,
	Launch = Launch,
	LoadedSources = LoadedSources,
	Locations = Locations,
	Modules = Modules,
	Next = Next,
	Pause = Pause,
	ReadMemory = ReadMemory,
	Restart = Restart,
	RestartFrame = RestartFrame,
	ReverseContinue = ReverseContinue,
	Scopes = Scopes,
	SetBreakpoints = SetBreakpoints,
	SetDataBreakpoints = SetDataBreakpoints,
	SetExceptionBreakpoints = SetExceptionBreakpoints,
	SetFunctionBreakpoints = SetFunctionBreakpoints,
	SetInstructionBreakpoints = SetInstructionBreakpoints,
	SetVariable = SetVariable,
	Source = Source,
	StackTrace = StackTrace,
	StepBack = StepBack,
	StepIn = StepIn,
	StepInTargets = StepInTargets,
	StepOut = StepOut,
	Terminate = Terminate,
	TerminateThreads = TerminateThreads,
	Threads = Threads,
	Variables = Variables,
	WriteMemory = WriteMemory,
	COMMAND = COMMAND,
}

return M
