local Breakpoint = require("dapc.rpc.event.Breakpoint")
local Capabilities = require("dapc.rpc.event.Capabilities")
local Continued = require("dapc.rpc.event.Continued")
local Exited = require("dapc.rpc.event.Exited")
local Initialized = require("dapc.rpc.event.Initialized")
local Invalidated = require("dapc.rpc.event.Invalidated")
local LoadedSource = require("dapc.rpc.event.LoadedSource")
local Memory = require("dapc.rpc.event.Memory")
local Module = require("dapc.rpc.event.Module")
local Output = require("dapc.rpc.event.Output")
local Process = require("dapc.rpc.event.Process")
local ProgressEnd = require("dapc.rpc.event.ProgressEnd")
local ProgressStart = require("dapc.rpc.event.ProgressStart")
local ProgressUpdate = require("dapc.rpc.event.ProgressUpdate")
local Stopped = require("dapc.rpc.event.Stopped")
local Terminated = require("dapc.rpc.event.Terminated")
local Thread = require("dapc.rpc.event.Thread")
local EVENT_TYPE = require("dapc.rpc.event.Event").EVENT_TYPE
local M = {
	Breakpoint = Breakpoint,
	Capabilities = Capabilities,
	Continued = Continued,
	Exited = Exited,
	Initialized = Initialized,
	Invalidated = Invalidated,
	LoadedSource = LoadedSource,
	Memory = Memory,
	Module = Module,
	Output = Output,
	Process = Process,
	ProgressEnd = ProgressEnd,
	ProgressStart = ProgressStart,
	ProgressUpdate = ProgressUpdate,
	Stopped = Stopped,
	Terminated = Terminated,
	Thread = Thread,
	EVENT_TYPE = EVENT_TYPE,
}

return M
